CREATE TABLE Kunde
(
    KId INTEGER AUTO_INCREMENT NOT NULL,
    Fornavn VARCHAR(50) NOT NULL,
    Etternavn VARCHAR(50) NOT NULL,
    Adresse VARCHAR(50) NOT NULL,
    PRIMARY KEY (KId)
);

CREATE TABLE Ordre
(
    OId INTEGER AUTO_INCREMENT NOT NULL,
    KId INTEGER,
    Varenavn VARCHAR(50),
    Pris DECIMAL(10,0),
    PRIMARY KEY (OId),
    FOREIGN KEY (KId) REFERENCES Kunde(KId)
);
